### ISSUE TITLE
More latest chapter issues

### ISSUE THREAD

**Issue by Weefsat** [doutatsu/kenmei#102]
Chuukan Kanrikoku Tonegawa and Berserk don't display the correct latest chapter. Likely the same issue as last time? Chapter uploaded then deleted.

![Manga](https://user-images.githubusercontent.com/39443093/69910617-97f90b00-140e-11ea-95b1-61d64bae42ae.png)
https://mangadex.org/manga/15691, https://mangadex.org/manga/607

**Comment by Weefsat** [comment]
In the case of Berserk, the issue is fixed now. But it used to have 0.04 set as the latest chapter.

**Comment by doutatsu** [comment]
Thanks, I've been seeing similar issues on my end and haven't yet pinned out on what else is at play, if any. I decided to bump the priority on adding "Something is wrong" button, so you can notify me in the app, if a chapter is out of date, etc.

**Comment by doutatsu** [comment]
@Weefsat I have updated `Chuukan Kanriroku Tonegawa` for you
