### ISSUE TITLE
First look/suggestions

### ISSUE THREAD

**Issue by thetobby** [doutatsu/kenmei#41]
- ~~Nickname based system to facilitating future social functions~~

- [x] Shows latest chapter 0, https://mangadex.org/manga/0000001 mentioned in #14 

- [ ] More secure passwords requirements? Currently, 01234567 is accepted

- ~~Blacklist for usernames~~
https://github.com/marteinn/The-Big-Username-Blacklist

- ~~Define nickname at signup, not bound to email~~

- ~~No progress bar on upload of json~~
- [x] No error message or upload of JSON files that are invalid.

**Comment by doutatsu** [comment]
1. Nickname based system to facilitating future social functions
2. Define nickname at signup, not bound to email
I don't expect any social functions, so I don't think I will be adding nicknames

3. More secure passwords requirements
Good shout, that's a simple addition 
4. No progress bar on upload of json
There is a progress bar, but only if your list is over 20 entries. You should still see it go to 100% after the import if you click on the import button again
5. No error message or upload of json files that are invalid.
Noted this bug, there is no error handling purely around file being uploaded, only during the processing

**Comment by Weefsat** [comment]
Three suggestions:

1. The text in the import box should say upload instead of download?

![Untitled](https://user-images.githubusercontent.com/39443093/66066174-51d81600-e549-11e9-96b0-6bc896aa8f73.png)

2. There could be the possibility to change manga names in the list. Some manga have long Japanese names and it's sometimes hard to tell them apart, especially if you have a long list and the manga hasn't been updated in a while. Extra credit if you can choose from alt names on Mangadex. 
(e.g If I look at "Hanzai Koushounin Minegishi Eitarou" I can't remember at all what that manga is. "The Negotiation Limerick File" alt name would remind me.)

3. An option that displays the date of the last released chapters so It's easier to tell if the scanlation died off or not.

**Comment by doutatsu** [comment]
> The text in the import box should say upload instead of download?

No, that's a link to Trackr.moe, wher you can download the JSON list, to be _uploaded_ on Kenmei

> There could be the possibility to change manga names in the list

I plan to support alt names. Possibly on series by series basis, as I prefer some in Japanese, while others in English myself

> An option that displays the date of the last released chapters so It's easier to tell if the scanlation died off or not.

What's the difference between showing date and showing time ago? Seeing `400 days ago` will give me the same information as seeing a date.

**Comment by doutatsu** [comment]
@Weefsat ☝️

**Comment by Weefsat** [comment]
Sorry for the late reply.
> No, that's a link to Trackr.moe, where you can download the JSON list, to be _uploaded_ on Kenmei

* [ ] Didn't notice the link, it is quite useful. Let me change my suggestion to link should be bolded and in a different color. 

> I plan to support alt names. Possibly on series by series basis, as I prefer some in Japanese, while others in English myself

Sounds perfect.

> What’s the difference between showing date and showing time ago? Seeing 400 days ago will give me the same information as seeing a date.

The TL; DR reply is: Currently we have neither of those. Days contract in weeks and weeks in months right away, so the data lacks granularity. I’m sending you a more in-depth response by email as I don’t think it fits well on the GitHub issue page.

Let me add even more requests:
* [ ] Read and unread manga should be separated in the list, with unread manga on top.
This is very important, as there are unread manga you put off reading for months and they will get completely lost in the long list of read manga without this feature.

* [ ] Manual updating options in the list. Sometimes the automatic updating fails and it’s good to have a backup. I used Trackr.moe “ignore latest” chapter and “I’ve read the latest chapter options” weekly. This is going to be especially important once more sites are added, as some are guaranteed to break updates when they get updated themselves.

* [ ] Add a completed manga list. It will reduce clutter in other lists. If you’re feeling ambitious you can find a way to automatically move manga from the reading to the completed list, once the final chapter is read.

**Comment by doutatsu** [comment]
> Read and unread manga should be separated in the list, with unread manga on top

Of course, this will become available as I properly start tracking last read and the next chapter available

> Manual updating options in the list. Sometimes the automatic updating fails and it’s good to have a backup

I see what you mean, I did have the same issue with Trackr. I have some ideas in general on how to do this well and I plan to make use of crowdsourced information (for example, being able to report real last chapter with a link. If enough people submit the same information, the system with automatically set that as the new latest chapter)

> Add a completed manga list

That's an interesting one. People will be able to create their own lists very soon, so you'll be able to do it manually. But I am also thinking of creating a _proper_ completed list with different behaviour to regular lists (like automatically being marked as finished)

**Comment by doutatsu** [comment]
@Weefsat I've finished working on this:
>  Read and unread manga should be separated in the list, with unread manga on top.

**Comment by Weefsat** [comment]
> @Weefsat I've finished working on this:
Awesome. This is enough to make me use Kenmei as my primary manga tracker. Really looking forward to getting automatic tracking back someday.

**Comment by doutatsu** [comment]
> This is enough to make me use Kenmei 

Awesome, glad to hear that! Keep any issues coming and I'll address them as soon as possible. 

> Really looking forward to getting automatic tracking back someday.

Can you remind me what you mean by this? I scanned this issue a bit, but didn't see what you referring to

**Comment by Weefsat** [comment]
> Can you remind me what you mean by this? I scanned this issue a bit, but didn't see what you referring to

Didn't mean something from this issue. I meant the "Auto-track chapters on page load" feature that trackr.moe has. It's the feature I miss most at the moment.

**Comment by doutatsu** [comment]
> Didn't mean something from this issue. I meant the "Auto-track chapters on page load" feature that trackr.moe has. It's the feature I miss most at the moment.

Oh, I see. I never even used that feature, as I often might open a chapter, but not finish it, so I prefer to manually check it off. But I am seeing the general usability of the extension, so I might work on it sooner than later. I'll put this specific feature into my backlog, thanks

**Comment by jackblk** [comment]
Hi there,

Can we have dark mode for the site, that would be great :D

**Comment by doutatsu** [comment]
@jackblk Its on the roadmap, but got quite a bit of more important features to ship first, but I'll get to it 👍

**Comment by LuposX** [comment]
Hi,
maybe add [Mangapark](https://mangapark.net/) to the supported sites.
