### ISSUE TITLE
Incorrect reference to ref?

### ISSUE THREAD

**Issue by rlightner** [doutatsu/kenmei#424]
https://github.com/doutatsu/kenmei/blob/6646c8d2cf1f45031b34694089db1d027a32cb8f/src/components/base_components/BaseModal.vue#L48

Looks like it should be `modalMask` and not `modal`?

**Comment by doutatsu** [comment]
@rlightner Have you seen any issues with body scroll locking? modal itself takes up the entire viewport, as can be seen here:
![image](https://user-images.githubusercontent.com/4270980/96380104-6f454580-1187-11eb-9d5f-df39aee2ef22.png)

I haven't seen any issues with the bodyscroll lock as a result, it is working as intended. But if you are experiencing issues, do let me know

**Comment by rlightner** [comment]
I see exceptions being written to the consol. $ref is pointing to an invalid element, then there is also a reference to `this.targetElement` which is also undefined. I'm just wondering if this is a by-product of copy paste code, or if they were intentionally written this way, and why?

**Comment by doutatsu** [comment]
@rlightner Can you share those console error screenshots then? I have went and checked if that was the case, but there are no console exceptions for me. This is a completely custom written code, there has been no copy pasting involved. I can only speculate that I had a modal reference before, but removed it while writing this, and as I tend to squash such changes, can't really see it in the original PR that introduced the modal.

But you are right, that there is no `modal` reference, so it's interesting that the re-enabling the scroll lock does work, even when the reference is `undefined`. I'll investigate further and change the code appropriately

**Comment by rlightner** [comment]
This is the error message showing up in the console. Nothing too spectacular. 

`enableBodyScroll unsuccessful - targetElement must be provided when calling enableBodyScroll on IOS devices.`

**Comment by doutatsu** [comment]
@rlightner Ah, interesting, I can see it in the source code for the bodyScroll lock. I haven't been testing on iOS devices, but I've dug out old iPad to see whatever it's actually not locking the scroll, as a result of this. And it does, which is indeed a bug, which is only present on iOS devices it seems. Thanks for reporting, I'll address this soon

**Comment by doutatsu** [comment]
Hey @rlightner, I've now confirmed the scroll lock working on iOS. So I expect you to not see the console warnings anymore, but let me know if you still do. Thanks for raising this issue 👍
