### ISSUE TITLE
Project lacks a license

### ISSUE THREAD

**Issue by RealKC** [doutatsu/kenmei#504]
The project should have a license, see this page https://choosealicense.com/no-permission/

**Comment by doutatsu** [comment]
@RealKC Yup, I am aware, I was looking over various licenses, but haven't decided on which one to use and then got busy with other things. I'll look into it again when I have time

**Comment by doutatsu** [comment]
I plan to remove this project from being open-source. I've wanted to see what it would bring, but in the end decided it's not the route I want to go for. I am keeping it open-source for now, to make use of the free tiers on some products I use, but will replace with paid tiers in the near future, and then make this a private project. As a result, there won't be a need to add a license
