### ISSUE TITLE
Feature request: RSS feeds for individual manga updates and overall

### ISSUE THREAD

**Issue by schklom** [doutatsu/kenmei#559]
**Is your feature request related to a problem? Please describe.**
I have to go on the website when I want to be alerted of updates

**Describe the solution you'd like**
RSS feeds: 1 per manga, and 1 for everything.
I would personally use 1 per manga, but I can definitely see some people wanting everything at once. MangaDex does it :P

**Describe alternatives you've considered**
I could save the login cookie and have a web-parser check updates and generate a feed by itself, but it would likely break at some point. Also, your website statistics would become skewed for people who do it, because a lot of their requests would be automated.

I'm not doing it though, it's too much of a pain.

**Additional context**

**Comment by doutatsu** [comment]
Kenmei is a platform, and many features are only possible by using the site as it is, it's tightly connected with the API. API itself is also private and there is no plans to make it public. As a result, Individual RSS feeds won't ever be added, that is not what this project is about.

There will be ability to receive notifications, with push notifications and emails eventually, as part of the product offering, but that functionality is planned for later.

**Comment by schklom** [comment]
Good to know that push notifications and emails will be available. In that situation, I agree RSS feeds aren't necessary.

Thanks for working on this service by the way, it's amazing ;)
