### ISSUE TITLE
Feature request: Docker image, or at least a Dockerfile

### ISSUE THREAD

**Issue by schklom** [doutatsu/kenmei#560]
**Is your feature request related to a problem? Please describe.**
I can see there are already images on DockerHub, but without instructions and the last update was 8 months ago.

**Describe the solution you'd like**
A Dockerfile for building an image of the site.
An image would be the best. I can help automating building a multi-platform image.

**Describe alternatives you've considered**
Hoping someone else makes a Dockerfile, as I don't have a lot of experience with them.

**Additional context**

**Comment by doutatsu** [comment]
I am not sure what you mean by there being an image on DockerHub... there is no Kenmei imagine anywhere, that I am aware off. I don't plan to make any, I am not quite even sure what purpose this suggestion brings

**Comment by schklom** [comment]
Thanks for the quick answer.
I was talking about https://hub.docker.com/r/kenmei/multi-client, and the others at https://hub.docker.com/search?q=kenmei&type=image

I was assuming they were yours, but I guess not.

The suggestion was to let users make their own kenmei website at home easily if they want, but I understand if that's not what you want :)

**Comment by doutatsu** [comment]
Huh, I see. Not sure who that is, but Kenmei is a name that others used, from what I've seen.
