### ISSUE TITLE
Invisible Manga

### ISSUE THREAD

**Issue by Odycay12** [doutatsu/kenmei#561]
**Describe the bug**
I have added the manga "I am the sorcer king" to my manga list, and yet it does not show up, nor does it allow me to re-add or delete it.

my account email is

**Expected behavior**
Manga Visible

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version 89.0.4389.82

**Comment by Odycay12** [comment]
Hello again, wow this is embarrassing. 20 years as a sysadmin and I didn't
even notice that there were other lists. I looked under plan to read, and
found the manga, seems i'm just dumb. Thanks very much for your help.

As well, thanks for removing my email, I wasn't really sure if i should add
it, but I figured what the heck, i only use that particular one for signing
up to non-critical stuff..

**Comment by doutatsu** [comment]
haha no worries @Odycay12, happens to the best of us. Feel free to send me an email if you have any other questions or issues, I'll probably reply there faster than on here
