### ISSUE TITLE
Naruto forbidden jutsu: hidden ninja-mode

### ISSUE THREAD

**Issue by mikken** [doutatsu/kenmei#57]
I tried to add Naruto from Mangadex:
https://mangadex.org/title/5/naruto

... and it did not appear in the list.

If I try that again, a message pops up saying "Manga already added".

**Comment by doutatsu** [comment]
Thanks for reporting @mikken, I've confirmed this is a bug. I'll fix it today

**Comment by doutatsu** [comment]
This bug has been now fixed, let me know if you still have the same issue or find anything else. Thanks for reporting again @mikken

**Comment by mikken** [comment]
Okay, however it's shown that latest chapter is 3.

**Comment by doutatsu** [comment]
@mikken There is a bug for some series, that show incorrect latest chapters, as been reported in #14. I will get to those eventually. Sorry about that

**Comment by doutatsu** [comment]
@mikken In case you missed it in the newsletter or twitter, the latest chapter bug has been fixed now, so you should see Naruto show the correct last chapter
