### ISSUE TITLE
Manga not updating.

### ISSUE THREAD

**Issue by Weefsat** [doutatsu/kenmei#87]
I believe Kanojo Gacha isn't updating. Two new chapters have been released and not tracked. I've had several other manga update in the meantime.
![Untitled](https://user-images.githubusercontent.com/39443093/68523737-9039c100-02bd-11ea-9449-b696e2dfe1da.png)

https://mangadex.org/manga/42843

**Comment by doutatsu** [comment]
Not sure yet why this hasn't been updated. Seeing as I the latest chapter logic works correctly when updating manually, I could only suspect it was either not included in the RSS feed (out of my hands) or there was an edge case with rss reading timing, so I skipped it 🤔Will investigate

**Comment by doutatsu** [comment]
With #116, I am now closing this issue and all new entries should be reported through the app itself
